-- =============================================================================
-- Randevu & Müşteri Takip — Supabase şeması
-- =============================================================================
-- Bu dosyayı Supabase panelinde SQL Editor'e yapıştırıp çalıştırın.
-- Her tablo, IndexedDB'deki bir "store" ile birebir eşleşir. Esnek alanları
-- korumak için kayıtlar `data jsonb` içinde tutulur; sık sorgulanan ilişkiler
-- (customer_id, appointment_id) ayrı sütun olarak da saklanır.
--
-- Güvenlik: Row Level Security (RLS) açıktır. Her satır, oluşturan kullanıcıya
-- (auth.uid()) bağlıdır; kullanıcılar yalnızca kendi verilerini görebilir.
-- =============================================================================

-- customers -------------------------------------------------------------------
create table if not exists public.customers (
  id         bigint generated by default as identity primary key,
  user_id    uuid not null default auth.uid() references auth.users (id) on delete cascade,
  data       jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

-- appointments ----------------------------------------------------------------
create table if not exists public.appointments (
  id          bigint generated by default as identity primary key,
  user_id     uuid not null default auth.uid() references auth.users (id) on delete cascade,
  customer_id bigint,
  data        jsonb not null default '{}'::jsonb,
  created_at  timestamptz not null default now()
);

-- todos -----------------------------------------------------------------------
create table if not exists public.todos (
  id         bigint generated by default as identity primary key,
  user_id    uuid not null default auth.uid() references auth.users (id) on delete cascade,
  data       jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

-- files -----------------------------------------------------------------------
create table if not exists public.files (
  id             bigint generated by default as identity primary key,
  user_id        uuid not null default auth.uid() references auth.users (id) on delete cascade,
  appointment_id bigint,
  data           jsonb not null default '{}'::jsonb,
  created_at     timestamptz not null default now()
);

-- settings --------------------------------------------------------------------
create table if not exists public.settings (
  user_id uuid not null default auth.uid() references auth.users (id) on delete cascade,
  key     text not null,
  value   jsonb,
  primary key (user_id, key)
);

-- Indeksler -------------------------------------------------------------------
create index if not exists appointments_user_idx     on public.appointments (user_id);
create index if not exists appointments_customer_idx on public.appointments (customer_id);
create index if not exists customers_user_idx        on public.customers (user_id);
create index if not exists todos_user_idx            on public.todos (user_id);
create index if not exists files_user_idx            on public.files (user_id);
create index if not exists files_appointment_idx     on public.files (appointment_id);

-- =============================================================================
-- Row Level Security
-- =============================================================================
alter table public.customers    enable row level security;
alter table public.appointments enable row level security;
alter table public.todos        enable row level security;
alter table public.files        enable row level security;
alter table public.settings     enable row level security;

-- Her tablo için: kullanıcı yalnızca kendi satırlarına erişebilir.
do $$
declare
  t text;
begin
  foreach t in array array['customers', 'appointments', 'todos', 'files', 'settings']
  loop
    execute format('drop policy if exists %I_select on public.%I;', t, t);
    execute format('drop policy if exists %I_insert on public.%I;', t, t);
    execute format('drop policy if exists %I_update on public.%I;', t, t);
    execute format('drop policy if exists %I_delete on public.%I;', t, t);

    execute format(
      'create policy %I_select on public.%I for select using (auth.uid() = user_id);', t, t);
    execute format(
      'create policy %I_insert on public.%I for insert with check (auth.uid() = user_id);', t, t);
    execute format(
      'create policy %I_update on public.%I for update using (auth.uid() = user_id) with check (auth.uid() = user_id);', t, t);
    execute format(
      'create policy %I_delete on public.%I for delete using (auth.uid() = user_id);', t, t);
  end loop;
end $$;
